### ISSUE TITLE
Allow to share a calendar in read only mode

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#417] opened 2015-09-24 15:21 UTC
Suggested by a user : he would like to share some of its calendar with friends, in read only mode (they can subscribe to the calendar but not update it)

**Comment by jsilvestre** [comment] 2016-01-11 17:07
It's a duplicate of https://github.com/cozy/cozy-calendar/issues/93, so I close this one.

**Closed by jsilvestre** 2016-01-11 17:07 UTC
Labels: duplicate
