### ISSUE TITLE
Share ics file

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-calendar#206] opened 2015-02-26 09:17 UTC
My roommate still use Google Calendar (I am a terrible evangelist). I need to share my calendar as an ICS file with a private URL and to display a remote (changing) ICS calendar inside my cozy.

Will work on it in a week-end.

**Comment by aenario** [comment] 2015-02-26 09:44
Note : if we do both, it will also solve the shared calendar between cozy problem (read-only)

**Comment by m4dz** [comment] 2015-02-26 11:58
Oooooh, I agree sooooooo much! I think this is definitely the way the things should be done :heart_eyes:.

**Comment by frankrousseau** [comment] 2015-02-26 12:09
Add link to #91 and #93

**Comment by aenario** [comment] 2015-02-26 12:24
subscribe @MartyLake

**Comment by MartyLake** [comment] 2015-02-26 16:05
Can't wait !!! :+1: =D

**Comment by jsilvestre** [comment] 2016-01-11 14:06
This issue is a duplicate of #91 and #93 so I'm closing it!

**Closed by jsilvestre** 2016-01-11 14:06 UTC
Labels: duplicate, enhancement
