### ISSUE TITLE
Add a quick navigation

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#451] opened 2015-12-02 15:25 UTC
We sould find a way to navigate quickly between months and years.
As requested [in the forum](https://forum.cozy.io/t/problemes-remarques-calendrier/1653).

**Comment by jsilvestre** [comment] 2016-01-11 17:02
Duplicate of #419, therefore I close the issue.

**Closed by jsilvestre** 2016-01-11 17:02 UTC
Labels: duplicate
