### ISSUE TITLE
Allow to add attachments to an event

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#454] opened 2015-12-04 10:56 UTC
Requested by [Charlotte](https://forum.cozy.io/t/problemes-remarques-calendrier/1653/13).

**Comment by poupotte** [comment] 2015-12-21 08:53
Related to https://github.com/cozy/cozy-calendar/issues/356

**Comment by jsilvestre** [comment] 2016-01-11 14:23
Since it's a duplicate of #356, I close the issue and links this one to the original one.

**Closed by jsilvestre** 2016-01-11 14:23 UTC
Labels: duplicate, enhancement
