### ISSUE TITLE
Allow to add exceptions to recurring events

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#344] opened 2015-07-24 17:06 UTC
As requested in [this post](https://forum.cozy.io/t/calendar-quelques-retours/875/31).
Depends on cozy/cozy-ical#36

**Comment by poupotte** [comment] 2015-12-21 08:55
Related to https://github.com/cozy/cozy-calendar/issues/238

**Comment by jsilvestre** [comment] 2016-01-11 14:25
Since it's a duplicate of #238, I close this issue and links this one to the original one.

**Closed by jsilvestre** 2016-01-11 14:25 UTC
Labels: duplicate, enhancement
