### ISSUE TITLE
Add a daily view

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#598] opened 2016-09-23 08:09 UTC
[Requested on the forum](https://forum.cozy.io/t/calendar-improvements/3466)

**Comment by jsilvestre** [comment] 2016-09-23 15:20
Thanks for reporting!

It is a duplicate of https://github.com/cozy/cozy-calendar/issues/471, so I close this one!

**Closed by jsilvestre** 2016-09-23 15:20 UTC
Labels: enhancement
