### ISSUE TITLE
Notification not sent for event created outside Cozy

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#429] opened 2015-10-05 14:36 UTC
As [reported by a user](https://forum.cozy.io/t/calendrier/364/34).

When one create an event in another calendar client and synchronize it with Cozy, no email alarm are sent.
We should create notification when syncing.

**Comment by jsilvestre** [comment] 2016-01-12 08:43
Also see https://github.com/cozy/cozy-calendar/issues/460.

**Comment by jsilvestre** [comment] 2016-01-12 11:41
This is a duplicate of https://github.com/cozy/cozy-calendar/issues/233.

**Closed by jsilvestre** 2016-01-12 11:41 UTC
Labels: bug, duplicate
