### ISSUE TITLE
Events of each day are sorted in reverse order

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#464] opened 2015-12-21 14:29 UTC
On list view, events on each day are sorted on reverse order.

**Comment by jsilvestre** [comment] 2016-01-07 16:29
I can't reproduce this, the order is chronological from top to bottom.

**Comment by clochix** [comment] 2016-01-08 08:39
Yes, but it's a little bit disappointing, I expected days to be sorted in reverse chronological order, but event on each day in chronological order.
I mean, we have:

 - Monday
    - 14:00 : xxx
    - 09:00 : xxx
 - Tuesday
    - 14:00 : xxx
    - 09:00 : xxx

and I expected

 - Monday
    - 09:00 : xxx
    - 14:00 : xxx
 - Tuesday
    - 09:00 : xxx
    - 14:00 : xxx

**Comment by jsilvestre** [comment] 2016-01-08 14:05
Oh right! I was looking at days, not times. Thanks for the precision!

**Comment by poupotte** [comment] 2016-07-27 08:36
This issue is now fixed.

**Closed by poupotte** 2016-07-27 08:36 UTC
Labels: 1 - Backlog, bug
