### ISSUE TITLE
escape in a modified popup should ask for confirmation before closing

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-calendar#404] opened 2015-09-04 11:01 UTC
1/ open an event popup (creation or modification)
2/ press esc
=> the popup is closed, it is fine.

1/ open an event popup (creation or modification)
2/ modify something (title)
3/ press esc
=> the popup is closed, it is not fine.

**Comment by poupotte** [comment] 2015-12-21 08:54
Related to https://github.com/cozy/cozy-calendar/issues/351

**Comment by jsilvestre** [comment] 2016-01-11 16:33
Since it's a duplicate of #351, I close and link to this issue.

**Closed by jsilvestre** 2016-01-11 16:33 UTC
Labels: duplicate
