### ISSUE TITLE
Email notifications are no more sent

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-calendar#250] opened 2015-05-12 11:06 UTC
An user (Martial) and I noticed that email invitation are not sent anymore. I don't have any error in my logs. @jsilvestre can you have a look at it?

**Comment by jsilvestre** [comment] 2015-06-01 10:24
Possible duplicate of #242

**Comment by jsilvestre** [comment] 2015-06-03 08:38
It is currently working. If it still doesn't work for the user, it may be self-hosted without a proper postfix configuration.

**Comment by f6fvy** [comment] 2015-06-04 11:56
It doesn't work for me either, despite being hosted on a cozycloud.cc instance :-(

**Comment by frankrousseau** [comment] 2015-06-04 17:01
:( It's weird, it works for me. In the next version of the Cozy Home, you will be able to send us the application logs. I hope it will help.

**Comment by frankrousseau** [comment] 2015-06-05 18:13
In fact the bug is that email notifications are no more sent.

**Comment by poupotte** [comment] 2015-06-16 10:03
There was an error on old data-system version. @f6fvy, can you try to update your stack ?

**Comment by f6fvy** [comment] 2015-06-17 10:59
I'm using one of your cozycloud.cc instance (upgraded to v2 by yourself I guess), and today I still don't receive any email event notification.

**Comment by clochix** [comment] 2015-07-13 11:08
Thanks a lot @jsilvestre, now a won't have any excuse if I forget an event ;-)

**Closed** 2015-07-17 09:17 UTC
Labels: bug
