### ISSUE TITLE
Import iCal malfunction

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-calendar#272] opened 2015-06-03 13:49 UTC
When importing an iCal calendar in Cozy, the "Confirm Import" button must be hit once for each imported event ! (v1.0.14).

**Comment by frankrousseau** [comment] 2015-06-06 11:37
Arg that looks to be a big bug.

**Comment by poupotte** [comment] 2015-06-17 08:34
I can't reproduce this issue. 
@f6fvy, can you test with the new calendar version (1.0.15) ? If problem is still present, can you give me more information about type of calendar that you try to import ?

**Comment by f6fvy** [comment] 2015-06-17 10:33
It seems to work now (1.0.15). I'm not exactly in the same state as my previous (failed) attempt as I already have calendars running on my instance, but I guess it is irrelevant.

**Comment by clochix** [comment] 2015-07-01 10:09
@f6fvy I'm unable to reproduce your initial bug, so I close this one. Don't hesitate to come back to us if you encounter other problems. And thanks for reporting ☺
Also, thank you @poupotte for investigating.

**Closed** 2015-07-02 11:56 UTC
Labels: bug
