### ISSUE TITLE
Add exception in recurrent events

### ISSUE THREAD

**Issue by encolpe** [cozy/cozy-calendar#498] opened 2016-03-15 17:49 UTC
Example: when you have a weekly meeting or training cancelled you cannot remove just one occurence.

**Comment by clochix** [comment] 2016-03-16 09:35
Hi @encolpe,

Thanks for asking for this feature. I'm closing this issue as this is a duplicate of #238, don't hesitate to add more comments there.

**Closed by clochix** 2016-03-16 09:35 UTC
